language: node_js

# https://github.com/nodejs/Release
# Specify current LTS version here, which is used for publishing to npm
node_js:
  - 10 # EOL: April 2021

os:
  - linux

# https://github.com/nodejs/Release
matrix:
  fast_finish: true
  include:
    - name: "Windows build"
      os: windows
      cache: false # windows cache uploads are slow
      env: YARN_GPG=no # starts gpg-agent that never exits

    - name: "macOS build"
      os: osx

    # Next node LTS version
    - node_js: 13 # EOL: June 2019
  allow_failures:
  - os: osx


services:
  - xvfb

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -q libxss-dev; fi

install:
  - yarn --frozen-lockfile --non-interactive --network-timeout 300000

script:
  - npm install -g nyc
  - npx nyc mocha
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn pack; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 30 yarn dist-all; fi

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: 
    secure: '$GITHUB_API_KEY'
  file:
    - 'dist/vagrant-manager.dmg'
    - 'dist/vagrant-manager.appx'
    - 'dist/vagrant-manager.exe'
    - 'dist/vagrant-manager-web-setup.exe'
    - 'dist/vagrant-manager-portable.exe'
    - 'dist/vagrant-manager-i386.AppImage'
    - 'dist/vagrant-manager-x86_64.AppImage'
    - 'dist/vagrant-manager-i686.rpm'
    - 'dist/vagrant-manager-x86_64.rpm'
    - 'dist/vagrant-manager-amd64.deb'
    - 'dist/vagrant-manager-i386.deb' 
  skip_cleanup: true
  on:
    tags: true
