image: Visual Studio 2017

platform:
  - x64

environment:	  
  GH_TOKEN:	      
    secure: QOQ4VyGatMnWZ9zFyw8D8DsI5ratn6Ethg+6F/tfXVfjSEMAr0JMZTafffArOtX1

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  
init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn install
  - yarn upgrade
  - npm install -g nyc

build_script:
  - yarn dist
  
test_script:
  - node --version
  - npm --version
  - npx nyc mocha
  - yarn dist

after_test:
- bash <(curl -s https://codecov.io/bash)
